Aim: To perform creating and accessing DataVector, MathsOperations, DataFramecreation, reading & writing, Handling DataFrame using Pandas and Numpy.

In [177]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [178]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr+1)
print(type(arr))

[2 3 4 5 6]
<class 'numpy.ndarray'>


In [179]:
import numpy as np

print(np.__version__)

1.26.4


1 - 1D array creation functions
The 1D array creation functions e.g. numpy.linspace and numpy.arange generally need at least two inputs, start and stop.

numpy.arange creates arrays with regularly incrementing values.

In [180]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [182]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 

In [183]:
np.linspace(1, 4, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

2 - 2D array creation functions
The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define properties of special matrices represented as 2D arrays.

np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:

In [184]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [185]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements. The two array creation functions can be helpful while doing linear algebra,

In [186]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [187]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [188]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [189]:
np.diag(a)

array([1, 4])

vander(x, n) defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, x where the highest polynomial order is n-1. This array creation routine is helpful in generating linear least squares models,

In [190]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [191]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [192]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

3 - general ndarray creation functions
The ndarray creation functions e.g. numpy.ones, numpy.zeros, and random define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

numpy.zeros will create an array filled with 0 values with the specified shape. The default dtype is float64:

In [193]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [194]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [195]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [196]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

The random method of the result of default_rng will create an array filled with random values between 0 and 1. It is included with the numpy.random library. Below, two arrays are created with shapes (2,3) and (2,3,2), respectively. The seed is set to 42 so you can reproduce these pseudorandom numbers:

In [197]:
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [198]:
default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

numpy.indices will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension:

In [199]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

Replicating, joining, or mutating existing arrays
Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array. 

In [200]:
a = np.array([1, 2, 3, 4, 5, 6])

In [201]:
b = a[:2]

In [202]:
b += 1

In [203]:
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In this example, you did not create a new array. You created a variable, b that viewed the first 2 elements of a. When you added 1 to b you would get the same result by adding 1 to a[:2]. If you want to create a new array, use the numpy.copy array creation routine as such:

In [204]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1

In [205]:
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [206]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

*Pandas*

In [207]:
import pandas as pd
pd.DataFrame({'A': [1, 2, 3]})

,A
0,1
1,2
2,3


Basic data structures in pandas
Pandas provides two types of classes for handling data:

Series: a one-dimensional labeled array holding data of any type
such as integers, strings, Python objects etc.

DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

Creating a Series by passing a list of values, letting pandas create a default RangeIndex.

In [208]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

Creating a DataFrame by passing a NumPy array with a datetime index using date_range() and labeled columns:

In [209]:
dates = pd.date_range("20240101", periods=6)

dates

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06'],
              dtype='datetime64[ns]', freq='D')

In [210]:
df = pd.DataFrame(np.random.randn(6, 4), 
                  index=dates, 
                  columns=list("ABCD"))

df

,A,B,C,D
2024-01-01,0.989797,-0.695065,-0.892579,0.412867
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-03,-0.623556,1.182610,-0.762588,1.297937
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260
2024-01-06,0.898888,1.149957,-2.281689,0.623494


Creating a DataFrame by passing a dictionary of objects where the keys are the column labels and the values are the column values.

In [211]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [212]:
df2

,A,B,C,D,E,F
0,1.0,2013-01-02,1.0,3,test,foo
1,1.0,2013-01-02,1.0,3,train,foo
2,1.0,2013-01-02,1.0,3,test,foo
3,1.0,2013-01-02,1.0,3,train,foo


In [213]:
#The columns of the resulting DataFrame have different dtypes:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [214]:
# Use DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame respectively:
df.head()

,A,B,C,D
2024-01-01,0.989797,-0.695065,-0.892579,0.412867
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-03,-0.623556,1.182610,-0.762588,1.297937
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260


In [215]:
df.tail(3)

,A,B,C,D
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260
2024-01-06,0.898888,1.149957,-2.281689,0.623494


In [216]:
# Display the DataFrame.index or DataFrame.columns:
df.index

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06'],
              dtype='datetime64[ns]', freq='D')

In [217]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [218]:
# Return a NumPy representation of the underlying data with DataFrame.to_numpy() without the index or column labels:
df.to_numpy()

array([[ 0.9897968 , -0.69506507, -0.89257896,  0.41286663],
       [ 0.86680755, -0.49448799,  0.84524006, -0.75707306],
       [-0.6235565 ,  1.18260987, -0.76258792,  1.29793746],
       [-0.55046268, -0.74657461,  1.51790145, -0.14040765],
       [-0.60166412,  1.13308764, -0.0439316 , -1.1832602 ],
       [ 0.89888756,  1.14995724, -2.28168948,  0.62349372]])

In [219]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [220]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [221]:
# describe() shows a quick statistic summary of your data:
df.describe()

,A,B,C,D
count,6.000000,6.000000,6.000000,6.000000
mean,0.163301,0.254921,-0.269608,0.042259
std,0.828599,0.989945,1.354149,0.919359
min,-0.623556,-0.746575,-2.281689,-1.183260
25%,-0.588864,-0.644921,-0.860081,-0.602907
50%,0.158172,0.319300,-0.403260,0.136229
75%,0.890868,1.145740,0.622947,0.570837
max,0.989797,1.182610,1.517901,1.297937


In [222]:
# Transposing your data:
df.T

,2024-01-01,2024-01-02,2024-01-03,2024-01-04,2024-01-05,2024-01-06
A,0.989797,0.866808,-0.623556,-0.550463,-0.601664,0.898888
B,-0.695065,-0.494488,1.182610,-0.746575,1.133088,1.149957
C,-0.892579,0.845240,-0.762588,1.517901,-0.043932,-2.281689
D,0.412867,-0.757073,1.297937,-0.140408,-1.183260,0.623494


In [223]:
# DataFrame.sort_index() sorts by an axis:
df.sort_index(axis=1, ascending=False)

,D,C,B,A
2024-01-01,0.412867,-0.892579,-0.695065,0.989797
2024-01-02,-0.757073,0.845240,-0.494488,0.866808
2024-01-03,1.297937,-0.762588,1.182610,-0.623556
2024-01-04,-0.140408,1.517901,-0.746575,-0.550463
2024-01-05,-1.183260,-0.043932,1.133088,-0.601664
2024-01-06,0.623494,-2.281689,1.149957,0.898888


In [224]:
# For a DataFrame, passing a single label selects a columns and yields a Series equivalent to df.A:
df["A"]

2024-01-01    0.989797
2024-01-02    0.866808
2024-01-03   -0.623556
2024-01-04   -0.550463
2024-01-05   -0.601664
2024-01-06    0.898888
Freq: D, Name: A, dtype: float64

In [225]:
# For a DataFrame, passing a slice : selects matching rows:
df[0:3]

,A,B,C,D
2024-01-01,0.989797,-0.695065,-0.892579,0.412867
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-03,-0.623556,1.182610,-0.762588,1.297937


In [226]:
df["20240102":"20240104"]

,A,B,C,D
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-03,-0.623556,1.182610,-0.762588,1.297937
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408


In [227]:
# Selecting a row matching a label: Selection by Label using DataFrame.loc() or DataFrame.at()
df.loc[dates[0]]

A    0.989797
B   -0.695065
C   -0.892579
D    0.412867
Name: 2024-01-01 00:00:00, dtype: float64

In [228]:
# Selecting all rows (:) with a select column labels:
df.loc[:, ["A", "B"]]

,A,B
2024-01-01,0.989797,-0.695065
2024-01-02,0.866808,-0.494488
2024-01-03,-0.623556,1.182610
2024-01-04,-0.550463,-0.746575
2024-01-05,-0.601664,1.133088
2024-01-06,0.898888,1.149957


In [229]:
# For label slicing, both endpoints are included:

df.loc["20240102":"20240104", ["A", "B"]]

,A,B
2024-01-02,0.866808,-0.494488
2024-01-03,-0.623556,1.182610
2024-01-04,-0.550463,-0.746575


In [230]:
# Selecting a single row and column label returns a scalar:

df.loc[dates[0], "A"]

0.9897967960148689

In [231]:
# For getting fast access to a scalar (equivalent to the prior method):
df.at[dates[0], "A"]

0.9897967960148689

In [232]:
# Selection by Position using DataFrame.iloc() or DataFrame.iat().
df.iloc[3]

A   -0.550463
B   -0.746575
C    1.517901
D   -0.140408
Name: 2024-01-04 00:00:00, dtype: float64

In [233]:
df.iloc[3:5, 0:2]

,A,B
2024-01-04,-0.550463,-0.746575
2024-01-05,-0.601664,1.133088


In [234]:
df.iloc[[1, 2, 4], [0, 2]]

,A,C
2024-01-02,0.866808,0.845240
2024-01-03,-0.623556,-0.762588
2024-01-05,-0.601664,-0.043932


In [235]:
df.iloc[1:3, :]

,A,B,C,D
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-03,-0.623556,1.182610,-0.762588,1.297937


In [236]:
df.iloc[:, 1:3]

,B,C
2024-01-01,-0.695065,-0.892579
2024-01-02,-0.494488,0.845240
2024-01-03,1.182610,-0.762588
2024-01-04,-0.746575,1.517901
2024-01-05,1.133088,-0.043932
2024-01-06,1.149957,-2.281689


In [237]:
df.iloc[1, 1]

-0.4944879853974703

In [238]:
# For getting fast access to a scalar (equivalent to the prior method):
df.iat[1, 1]

-0.4944879853974703

Boolean indexing

In [239]:
# Select rows where df.A is greater than 0.
df[df["A"] > 0]

,A,B,C,D
2024-01-01,0.989797,-0.695065,-0.892579,0.412867
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-06,0.898888,1.149957,-2.281689,0.623494


In [240]:
# Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

,A,B,C,D
2024-01-01,0.989797,NaN,NaN,0.412867
2024-01-02,0.866808,NaN,0.845240,NaN
2024-01-03,NaN,1.182610,NaN,1.297937
2024-01-04,NaN,NaN,1.517901,NaN
2024-01-05,NaN,1.133088,NaN,NaN
2024-01-06,0.898888,1.149957,NaN,0.623494


In [241]:
# Using isin() method for filtering:
df3 = df.copy()
df3

,A,B,C,D
2024-01-01,0.989797,-0.695065,-0.892579,0.412867
2024-01-02,0.866808,-0.494488,0.845240,-0.757073
2024-01-03,-0.623556,1.182610,-0.762588,1.297937
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260
2024-01-06,0.898888,1.149957,-2.281689,0.623494


In [242]:
df3["E"] = ["one", "one", "two", "three", "four", "three"]
df3

,A,B,C,D,E
2024-01-01,0.989797,-0.695065,-0.892579,0.412867,one
2024-01-02,0.866808,-0.494488,0.845240,-0.757073,one
2024-01-03,-0.623556,1.182610,-0.762588,1.297937,two
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408,three
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260,four
2024-01-06,0.898888,1.149957,-2.281689,0.623494,three


In [243]:
df3[df3["E"].isin(["two", "four"])]

,A,B,C,D,E
2024-01-03,-0.623556,1.182610,-0.762588,1.297937,two
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260,four


Setting

In [244]:
# Setting a new column automatically aligns the data by the indexes:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20250102", periods=6))
s1

2025-01-02    1
2025-01-03    2
2025-01-04    3
2025-01-05    4
2025-01-06    5
2025-01-07    6
Freq: D, dtype: int64

In [245]:
df["F"] = s1

In [246]:
df

,A,B,C,D,F
2024-01-01,0.989797,-0.695065,-0.892579,0.412867,NaN
2024-01-02,0.866808,-0.494488,0.845240,-0.757073,NaN
2024-01-03,-0.623556,1.182610,-0.762588,1.297937,NaN
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408,NaN
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260,NaN
2024-01-06,0.898888,1.149957,-2.281689,0.623494,NaN


In [247]:
# Setting values by label:
df.at[dates[0], "A"] = 0
df

,A,B,C,D,F
2024-01-01,0.000000,-0.695065,-0.892579,0.412867,NaN
2024-01-02,0.866808,-0.494488,0.845240,-0.757073,NaN
2024-01-03,-0.623556,1.182610,-0.762588,1.297937,NaN
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408,NaN
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260,NaN
2024-01-06,0.898888,1.149957,-2.281689,0.623494,NaN


In [248]:
# Setting values by position:
df.iat[0, 1] = 0
df


,A,B,C,D,F
2024-01-01,0.000000,0.000000,-0.892579,0.412867,NaN
2024-01-02,0.866808,-0.494488,0.845240,-0.757073,NaN
2024-01-03,-0.623556,1.182610,-0.762588,1.297937,NaN
2024-01-04,-0.550463,-0.746575,1.517901,-0.140408,NaN
2024-01-05,-0.601664,1.133088,-0.043932,-1.183260,NaN
2024-01-06,0.898888,1.149957,-2.281689,0.623494,NaN


In [249]:
# Setting by assigning with a NumPy array:
df.loc[:, "D"] = np.array([5] * len(df))
df

,A,B,C,D,F
2024-01-01,0.000000,0.000000,-0.892579,5.0,NaN
2024-01-02,0.866808,-0.494488,0.845240,5.0,NaN
2024-01-03,-0.623556,1.182610,-0.762588,5.0,NaN
2024-01-04,-0.550463,-0.746575,1.517901,5.0,NaN
2024-01-05,-0.601664,1.133088,-0.043932,5.0,NaN
2024-01-06,0.898888,1.149957,-2.281689,5.0,NaN


In [250]:
# A where operation with setting:
df2 = df.copy()
df2

,A,B,C,D,F
2024-01-01,0.000000,0.000000,-0.892579,5.0,NaN
2024-01-02,0.866808,-0.494488,0.845240,5.0,NaN
2024-01-03,-0.623556,1.182610,-0.762588,5.0,NaN
2024-01-04,-0.550463,-0.746575,1.517901,5.0,NaN
2024-01-05,-0.601664,1.133088,-0.043932,5.0,NaN
2024-01-06,0.898888,1.149957,-2.281689,5.0,NaN


In [251]:
df2[df2 > 0] = -df2
df2

,A,B,C,D,F
2024-01-01,0.000000,0.000000,-0.892579,-5.0,NaN
2024-01-02,-0.866808,-0.494488,-0.845240,-5.0,NaN
2024-01-03,-0.623556,-1.182610,-0.762588,-5.0,NaN
2024-01-04,-0.550463,-0.746575,-1.517901,-5.0,NaN
2024-01-05,-0.601664,-1.133088,-0.043932,-5.0,NaN
2024-01-06,-0.898888,-1.149957,-2.281689,-5.0,NaN


**Missing data**
For NumPy data types, np.nan represents missing data. It is by default not included in computations.

In [252]:
# Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1

,A,B,C,D,F,E
2024-01-01,0.000000,0.000000,-0.892579,5.0,NaN,NaN
2024-01-02,0.866808,-0.494488,0.845240,5.0,NaN,NaN
2024-01-03,-0.623556,1.182610,-0.762588,5.0,NaN,NaN
2024-01-04,-0.550463,-0.746575,1.517901,5.0,NaN,NaN


In [253]:
df1.loc[dates[0] : dates[1], "E"] = 1
df1

,A,B,C,D,F,E
2024-01-01,0.000000,0.000000,-0.892579,5.0,NaN,1.0
2024-01-02,0.866808,-0.494488,0.845240,5.0,NaN,1.0
2024-01-03,-0.623556,1.182610,-0.762588,5.0,NaN,NaN
2024-01-04,-0.550463,-0.746575,1.517901,5.0,NaN,NaN


In [254]:
# DataFrame.dropna() drops any rows that have missing data:
df1.dropna(how="any")

,A,B,C,D,F,E


In [255]:
# DataFrame.fillna() fills missing data:
df1.fillna(value=5)

,A,B,C,D,F,E
2024-01-01,0.000000,0.000000,-0.892579,5.0,5.0,1.0
2024-01-02,0.866808,-0.494488,0.845240,5.0,5.0,1.0
2024-01-03,-0.623556,1.182610,-0.762588,5.0,5.0,5.0
2024-01-04,-0.550463,-0.746575,1.517901,5.0,5.0,5.0


In [256]:
# isna() gets the boolean mask where values are nan:
pd.isna(df1)

,A,B,C,D,F,E
2024-01-01,False,False,False,False,True,False
2024-01-02,False,False,False,False,True,False
2024-01-03,False,False,False,False,True,True
2024-01-04,False,False,False,False,True,True


# Operations

In [257]:
# Calculate the mean value for each column:
df.mean()

A   -0.001665
B    0.370765
C   -0.269608
D    5.000000
F         NaN
dtype: float64

In [258]:
# Calculate the mean value for each row:
df.mean(axis=1)

2024-01-01    1.026855
2024-01-02    1.554390
2024-01-03    1.199116
2024-01-04    1.305216
2024-01-05    1.371873
2024-01-06    1.191789
Freq: D, dtype: float64

# Value Counts

In [259]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    4
1    2
2    5
3    5
4    1
5    2
6    4
7    6
8    6
9    2
dtype: int32

In [260]:
s.value_counts()

2    3
4    2
5    2
6    2
1    1
Name: count, dtype: int64

# String Methods
Series is equipped with a set of string processing methods in the str attribute that make it easy to operate on each element of the array, as in the code snippet below. See more at Vectorized String Methods.

In [261]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s

0       A
1       B
2       C
3    Aaba
4    Baca
5     NaN
6    CABA
7     dog
8     cat
dtype: object

In [262]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [263]:
s.str.upper()

0       A
1       B
2       C
3    AABA
4    BACA
5     NaN
6    CABA
7     DOG
8     CAT
dtype: object

In [264]:
# Concatenating pandas objects together row-wise with concat():
df = pd.DataFrame(np.random.randn(10, 4))
df

,0,1,2,3
0,-1.229683,-0.197405,-0.145762,-2.044668
1,-1.556063,-0.228765,-2.041829,-1.212386
2,0.469218,-0.858228,-1.206227,-2.314386
3,-2.080832,-0.734374,-0.168475,-0.596102
4,0.091414,0.308534,-0.673054,-0.503474
5,1.013585,-0.685575,0.217185,1.443219
6,-0.635751,-0.351625,0.042247,-0.687440
7,-0.424826,0.290602,-0.357905,0.010533
8,-1.598182,-0.199086,0.682746,0.374078
9,0.832853,-0.009929,3.027273,-0.042410


In [265]:
# break it into pieces
pieces = [df[:3], df[3:7], df[7:]]
pieces

[          0         1         2         3
 0 -1.229683 -0.197405 -0.145762 -2.044668
 1 -1.556063 -0.228765 -2.041829 -1.212386
 2  0.469218 -0.858228 -1.206227 -2.314386,
           0         1         2         3
 3 -2.080832 -0.734374 -0.168475 -0.596102
 4  0.091414  0.308534 -0.673054 -0.503474
 5  1.013585 -0.685575  0.217185  1.443219
 6 -0.635751 -0.351625  0.042247 -0.687440,
           0         1         2         3
 7 -0.424826  0.290602 -0.357905  0.010533
 8 -1.598182 -0.199086  0.682746  0.374078
 9  0.832853 -0.009929  3.027273 -0.042410]

In [266]:
pd.concat(pieces)

,0,1,2,3
0,-1.229683,-0.197405,-0.145762,-2.044668
1,-1.556063,-0.228765,-2.041829,-1.212386
2,0.469218,-0.858228,-1.206227,-2.314386
3,-2.080832,-0.734374,-0.168475,-0.596102
4,0.091414,0.308534,-0.673054,-0.503474
5,1.013585,-0.685575,0.217185,1.443219
6,-0.635751,-0.351625,0.042247,-0.687440
7,-0.424826,0.290602,-0.357905,0.010533
8,-1.598182,-0.199086,0.682746,0.374078
9,0.832853,-0.009929,3.027273,-0.042410


In [267]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [268]:
left

,key,lval
0,foo,1
1,foo,2


In [269]:
right

,key,rval
0,foo,4
1,foo,5


In [270]:
pd.merge(left, right, on="key")

,key,lval,rval
0,foo,1,4
1,foo,1,5
2,foo,2,4
3,foo,2,5


In [271]:
# merge() on unique keys:
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})

right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})


In [272]:
left

,key,lval
0,foo,1
1,bar,2


In [273]:
right

,key,rval
0,foo,4
1,bar,5


In [274]:
pd.merge(left, right, on="key")

,key,lval,rval
0,foo,1,4
1,bar,2,5


# Categoricals
pandas can include categorical data in a DataFrame.

In [275]:
df = pd.DataFrame( {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]})
df

,id,raw_grade
0,1,a
1,2,b
2,3,b
3,4,a
4,5,a
5,6,e


In [276]:
type(df)

pandas.core.frame.DataFrame

In [277]:
df["grade"] = df["raw_grade"].astype("category")
df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'e']

In [278]:
new_categories = ["very good", "good", "very bad"]

df["grade"] = df["grade"].cat.rename_categories(new_categories)
df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (3, object): ['very good', 'good', 'very bad']

# Importing and exporting data

In [279]:
df = pd.DataFrame(np.random.randint(0, 5, (10, 5)))
df

,0,1,2,3,4
0,3,0,3,2,3
1,4,0,2,1,4
2,4,1,4,2,2
3,1,3,0,0,1
4,3,4,1,0,2
5,3,3,0,0,3
6,3,1,0,4,1
7,0,4,3,2,1
8,1,4,2,1,4
9,2,2,2,3,4


In [280]:
df.to_csv("firstfile.csv")

In [281]:
pd.read_csv("firstfile.csv")

,Unnamed: 0,0,1,2,3,4
0,0,3,0,3,2,3
1,1,4,0,2,1,4
2,2,4,1,4,2,2
3,3,1,3,0,0,1
4,4,3,4,1,0,2
5,5,3,3,0,0,3
6,6,3,1,0,4,1
7,7,0,4,3,2,1
8,8,1,4,2,1,4
9,9,2,2,2,3,4


A Parquet file is a column-oriented data file format that's designed to store and retrieve data efficiently: 
Columnar: Parquet stores the values of each table column next to each other, instead of each record. 
Open source: Parquet is free to use and licensed under the Apache Hadoop license. 
Self-describing: Parquet files contain metadata, including the schema and structure, in addition to data. 
Efficient compression: Parquet uses compression and encoding schemes to optimize files for query performance. 
Fast queries: Parquet allows users to fetch specific column values without reading the entire row of data. 
Compatible with many systems: Parquet is supported by many data processing systems, including Spark SQL. 
Parquet files are well suited for handling large volumes of complex data. They're more efficient than other unstructured data formats, like CSV or JSON, and require less storage space

In [282]:
df.to_parquet("firstfile.parquet")

In [283]:
pd.read_parquet("firstfile.parquet")

,0,1,2,3,4
0,3,0,3,2,3
1,4,0,2,1,4
2,4,1,4,2,2
3,1,3,0,0,1
4,3,4,1,0,2
5,3,3,0,0,3
6,3,1,0,4,1
7,0,4,3,2,1
8,1,4,2,1,4
9,2,2,2,3,4


In [284]:
df.to_excel("firstfile.xlsx", sheet_name="Sheet1")

In [285]:
pd.read_excel("firstfile.xlsx", "Sheet1")

,Unnamed: 0,0,1,2,3,4
0,0,3,0,3,2,3
1,1,4,0,2,1,4
2,2,4,1,4,2,2
3,3,1,3,0,0,1
4,4,3,4,1,0,2
5,5,3,3,0,0,3
6,6,3,1,0,4,1
7,7,0,4,3,2,1
8,8,1,4,2,1,4
9,9,2,2,2,3,4
