# Aim: To perform Naïve Bayes and K-NN (k-nearest neighbor) classification using sklearn package in python

**Why is it called Naïve Bayes?**

# We have to create a Naïve Bayes model to classify flowers into one of the three given possible classes

In [68]:
# Import libraries
import pandas as pd
import numpy as np
import sklearn.datasets as data

In [69]:
# Read or Generate the dataset for machine learning task
d1 = data.load_iris()
d1

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [70]:
# PLACE THE IRIS DATA IN A PANDAS 
# DATAFRAME 
iris = pd.DataFrame(data=d1.data,columns=d1.feature_names) 
iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [71]:
# Add the target variable to the dataframe
iris['target'] = d1.target

In [72]:
iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [73]:
# Arrange data into a features matrix (X) and target vector (y)
# Create the Predictor and Target sets
X= d1.data
y= d1.target

In [74]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [75]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state = 99)

In [76]:
# Choose a class of model by importing the appropriate estimator class from Scikit-Learn
from sklearn.naive_bayes import GaussianNB
nv= GaussianNB()

In [77]:
# Fit the model to your training data by calling the fit() method of the model instance
nv.fit(X_train,y_train)

GaussianNB()

In [78]:
# Test the classifier on Test data
y_pred = nv.predict(X_test) # y_pred is predicted output

In [79]:
# Compare predicted output with actual output to find accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.9555555555555556
[[12  0  0]
 [ 0 17  1]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.94      0.94      0.94        18
           2       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [86]:
new_data=[[6.5,3.1,1.2,1.5]]

In [87]:
# Predict target values

predicted_target = nv.predict(new_data) 
print(predicted_target) 

[1]


# K-NN (k-nearest neighbor) classification 

In [16]:
# Choose a class of model by importing the appropriate estimator class from Scikit-Learn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [17]:
# Fit the model to your training data by calling the fit() method of the model instance
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
# Test the classifier on Test data
y_pred = knn.predict(X_test) # y_pred is predicted output

In [19]:
# Compare predicted output with actual output to find accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.9333333333333333
[[12  0  0]
 [ 0 16  2]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.94      0.89      0.91        18
           2       0.88      0.93      0.90        15

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45



In [20]:
# Let's do the same thing with titanic dataset
# Import nessasary libraries
import pandas as pd 
from sklearn.model_selection import train_test_split

In [21]:
data=pd.read_csv("train.csv")

In [22]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [23]:
#Using drop function to exclude collums I won't need. The parameter inplace true will change the table 
data.drop(["PassengerId", "Name","SibSp","Parch","Ticket","Fare","Cabin","Embarked"], axis="columns",inplace=True)
data.head()

,Survived,Pclass,Sex,Age
0,0,3,male,22.0
1,1,1,female,38.0
2,1,3,female,26.0
3,1,1,female,35.0
4,0,3,male,35.0


In [24]:
X = data.drop(["Survived"],axis="columns")
# For the variable Y I can simply select the column Survived 
y = data["Survived"] #Another way to declare: Y = data.Survived 
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [25]:
#The next step: create a pattern
#Pattern: male = 0 / female = 1
#This method map will create synonims in a dictionary
X.Sex = X.Sex.map({"male":0,"female":1})
X.head()

,Pclass,Sex,Age
0,3,0,22.0
1,1,1,38.0
2,3,1,26.0
3,1,1,35.0
4,3,0,35.0


In [26]:
#Some filles with the ages are empy. Checkin out the first 40 lines
X.Age[0:40]

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17     NaN
18    31.0
19     NaN
20    35.0
21    34.0
22    15.0
23    28.0
24     8.0
25    38.0
26     NaN
27    19.0
28     NaN
29     NaN
30    40.0
31     NaN
32     NaN
33    66.0
34    28.0
35    42.0
36     NaN
37    21.0
38    18.0
39    14.0
Name: Age, dtype: float64

In [27]:
# use when someone used dataset from kaggle

# To fix this, we will use method fillna(). Inside the brackets I'll put the information to replace, which will be the mean
X.Age = X.Age.fillna(X.Age.mean())
X.Age[0:40]

0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
5     29.699118
6     54.000000
7      2.000000
8     27.000000
9     14.000000
10     4.000000
11    58.000000
12    20.000000
13    39.000000
14    14.000000
15    55.000000
16     2.000000
17    29.699118
18    31.000000
19    29.699118
20    35.000000
21    34.000000
22    15.000000
23    28.000000
24     8.000000
25    38.000000
26    29.699118
27    19.000000
28    29.699118
29    29.699118
30    40.000000
31    29.699118
32    29.699118
33    66.000000
34    28.000000
35    42.000000
36    29.699118
37    21.000000
38    18.000000
39    14.000000
Name: Age, dtype: float64

In [28]:
#Now want data to training (80%) and testing (20%)
train_test_split(X,y,train_size = 0.8) # It is automaticaly setting 0.2 for testing
# X_training [712 rows x 3 columns]
# X_test [179 rows x 3 columns]
# Y_training[Length: 712]
# Y_test[Length: 179]

[     Pclass  Sex        Age
 658       2    0  23.000000
 414       3    0  44.000000
 307       1    1  17.000000
 36        3    0  29.699118
 504       1    1  16.000000
 ..      ...  ...        ...
 860       3    0  41.000000
 565       3    0  24.000000
 76        3    0  29.699118
 780       3    1  13.000000
 689       1    1  15.000000
 
 [712 rows x 3 columns],
      Pclass  Sex        Age
 729       3    1  25.000000
 679       1    0  36.000000
 429       3    0  32.000000
 371       3    0  18.000000
 281       3    0  28.000000
 ..      ...  ...        ...
 687       3    0  19.000000
 176       3    0  29.699118
 89        3    0  24.000000
 787       3    0   8.000000
 22        3    1  15.000000
 
 [179 rows x 3 columns],
 658    0
 414    1
 307    1
 36     1
 504    1
       ..
 860    0
 565    0
 76     0
 780    1
 689    1
 Name: Survived, Length: 712, dtype: int64,
 729    0
 679    1
 429    1
 371    0
 281    0
       ..
 687    0
 176    0
 89     0
 787  

In [29]:
# Now create 4 variables to place each parameter
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size = 0.8)

In [30]:
# Choose a class of model by importing the appropriate estimator class from Scikit-Learn
from sklearn.naive_bayes import GaussianNB
nv= GaussianNB()

In [31]:
# Fit the model to your training data by calling the fit() method of the model instance
nv.fit(X_train,y_train)

GaussianNB()

In [32]:
# Test the classifier on Test data
y_pred = nv.predict(X_test) # y_pred is predicted output

In [33]:
# Compare predicted output with actual output to find accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.8100558659217877
[[90 19]
 [15 55]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       109
           1       0.74      0.79      0.76        70

    accuracy                           0.81       179
   macro avg       0.80      0.81      0.80       179
weighted avg       0.81      0.81      0.81       179



In [58]:
# Choose a class of model by importing the appropriate estimator class from Scikit-Learn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [59]:
# Fit the model to your training data by calling the fit() method of the model instance
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [60]:
# Test the classifier on Test data
y_pred = knn.predict(X_test) # y_pred is predicted output

In [61]:
# Compare predicted output with actual output to find accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

0.7653631284916201
[[90 19]
 [23 47]]
              precision    recall  f1-score   support

           0       0.80      0.83      0.81       109
           1       0.71      0.67      0.69        70

    accuracy                           0.77       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.76      0.77      0.76       179

